### PR TITLE
Adding ability to export clips using bookmarks

### PR DESCRIPTION
**Pull request by Blueboom42**
The new functionality adds a new Export Clips option to the File->Export menu. This will create a spliced video and funscript from the start of one bookmark to the next. End Markers will not create a clip after them. 

The video is re-encoded using ffmpeg to allow for frame perfect splits. This is a slow process and does cause OpenFunscripter to freeze until the operation is successfully completed, though the progress can be monitored in the debug window. This isn't necessarily a problem but something that users should be made aware of.

### CODE REVIEW

**Comment by Blueboom42** [comment]
Should have rebased before submitting the pull request. The code needs to be updated for the changes made to Bookmarks

**Comment by Blueboom42** [comment]
PR is now ready for review

**Comment by gagax1234** [comment]
> Should have rebased before submitting the pull request. The code needs to be updated for the changes made to Bookmarks

Sorry, I'm changing "time" to be consistently floating point seconds accross the application.
Which makes thing a lot nicer & precise.

I'm just going to merge this I hope you don't mind me changing some things.

**Comment by gagax1234** [comment]
So a couple things I changed was adding a little blocking dialog that prevents you from doing anything while the export is happening but doesn't freeze the application.
And the slicing for multi-axis scripts.
I also moved the "Export Clips" to the bookmark menu just because I think it's easier to find there.

**Pull request merged**
